# Generated by Django 2.2.5 on 2019-10-17 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authenticationss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=1000)),
                ('PhoneNumber', models.CharField(blank=True, max_length=1000)),
                ('Email', models.CharField(blank=True, max_length=1000)),
                ('Answers', models.CharField(blank=True, max_length=5000)),
                ('OTP', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='QandAModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Questions', models.CharField(blank=True, max_length=1000)),
                ('Answers', models.CharField(blank=True, max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='StudentBotUsersDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=1000)),
                ('PhoneNumber', models.CharField(blank=True, max_length=1000)),
                ('Email', models.CharField(blank=True, max_length=1000)),
                ('Answers', models.CharField(blank=True, max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='ChatBotAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
